---
dataset:
  data_path: /home/ubuntu/TorchGNN_project/data_temp/exp2_train_100_0.3/meta_group_4_0
  d: 40
  loader_name: Torchloader
  name : TorchGeoLoader
  num_node: 100
  split: train
exp_dir: GNN_exp/V=100/meta_learn_val/exp5
exp_name: TorchGNN_meta
gpus:
- 0
model:
  temp : true
  aggregate_type : att
  degree_emb: false
  drop_prob: 0
  hidden_dim: 64
  loss: KL-pq
  name: TorchGNN_meta
  num_prop: 10
  jumping : false
  skip_connection : false
  interpol : false
  master_node : false
  masking : false
  masking_number : []
  SSL : false
  train_pretext : false
  random_init : false
runner: Modular_meta_learning
seed: 1234
test:
  optim_step: 1
  batch_size: 1
  num_workers: 0
  test_model: ../GNN_exp/
train:
  batch_size: 20
  meta_copy: 3
  display_iter: 13000
  is_resume: false
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  max_epoch: 300
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_model: None
  shuffle: false
  snapshot_epoch: 20000
  valid_epoch: 1
  wd: 0.0
  init_temp: 0.0001
use_gpu: true
